title: Abishek V
url: "https://abishek-v.github.io"
baseurl: "/know-me"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.linkedin.com/in/abishek-v"
footer_text: Say Hello...!

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
